sudo: false
language: node_js
services: 
  - mongodb
  - redis-server
env:
  - MONGOLAB_URL=mongodb://127.0.0.1/snipe LOG_MONGOLAB_URL=mongodb://127.0.0.1/snipelogs REDIS_URL=redis://127.0.0.1/1 SECURE_MODE=true NO_CACHE=no
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
node_js:
  - '12'
before_script:
  - sleep 15
  - npm install -g mocha eslint
install:
  - npm install
script:
  - npm test
  - npm run lint
