version: '3'
services:

    # The Application
    api:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        links:
            - redis
            - mongo
        environment:
            - MONGOLAB_URL=mongodb://mongo/giro
            - REDIS_URL=redis://redis:6379/1
        restart: always

    # MongoDB Admin
    mongoadmin:
        image: mongo-express
        links:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
        restart: always
        ports:
            - "8081:8081"

    # Redis
    redis:
        image: redis
        restart: always

    # Mongo
    mongo:
        image: mongo:3.6
        restart: always
